name: build
on: [workflow_call]
jobs:
  build:
    container:
       image: registry.opensuse.org/opensuse/bci/nodejs:latest
    environment: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup Python
        run: |
            zypper in -y python312 python312-pip
      - name: Show Python version
        run: python3.12 --version
      - name: Install environment
        run: |
          mkdir -p .venv/cienv
          python3.12 -m venv ./venv/cienv
          source ./venv/cienv/bin/activate
          export FLIT_ROOT_INSTALL=1 # this is not real root
          pip install flit==3.12.0
          flit install
      - name: Code formatting
        run: |
          source ./venv/cienv/bin/activate 
          black --check .  
      - name: Building library
        run: |
          source ./venv/cienv/bin/activate
          export SOURCE_DATE_EPOCH=$(date +%s)
          flit build
      - name: Code analysis
        run: |
          source ./venv/cienv/bin/activate
          prospector --profile .prospector.yaml --zero-exit > ./prospector.json
      - name: Run unit test
        run: |
           source ./venv/cienv/bin/activate
           coverage run -m unittest
           coverage report
           coverage json
           coverage lcov